name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
  
      - name: Run dotnet restore
        run: dotnet restore VisionHub.sln
        
      - name: Build solution
        run: dotnet build VisionHub.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --logger "console;verbosity=detailed"
